# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/apikey.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x19headscale/v1/apikey.proto\x12\x0cheadscale.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n\x06\x41piKey\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06prefix\x18\x02 \x01(\t\x12.\n\nexpiration\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tlast_seen\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"E\n\x13\x43reateApiKeyRequest\x12.\n\nexpiration\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\'\n\x14\x43reateApiKeyResponse\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"%\n\x13\x45xpireApiKeyRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\"\x16\n\x14\x45xpireApiKeyResponse\"\x14\n\x12ListApiKeysRequest\"=\n\x13ListApiKeysResponse\x12&\n\x08\x61pi_keys\x18\x01 \x03(\x0b\x32\x14.headscale.v1.ApiKey\"%\n\x13\x44\x65leteApiKeyRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\"\x16\n\x14\x44\x65leteApiKeyResponseB)Z\'github.com/juanfont/headscale/gen/go/v1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Headscale
  module V1
    ApiKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ApiKey").msgclass
    CreateApiKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreateApiKeyRequest").msgclass
    CreateApiKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreateApiKeyResponse").msgclass
    ExpireApiKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ExpireApiKeyRequest").msgclass
    ExpireApiKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ExpireApiKeyResponse").msgclass
    ListApiKeysRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListApiKeysRequest").msgclass
    ListApiKeysResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListApiKeysResponse").msgclass
    DeleteApiKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteApiKeyRequest").msgclass
    DeleteApiKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteApiKeyResponse").msgclass
  end
end
