# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: headscale/v1/headscale.proto for package 'headscale.v1'

require 'grpc'
require 'headscale/v1/headscale_pb'

module Headscale
  module V1
    module HeadscaleService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'headscale.v1.HeadscaleService'

        # --- User start ---
        rpc :CreateUser, ::Headscale::V1::CreateUserRequest, ::Headscale::V1::CreateUserResponse
        rpc :RenameUser, ::Headscale::V1::RenameUserRequest, ::Headscale::V1::RenameUserResponse
        rpc :DeleteUser, ::Headscale::V1::DeleteUserRequest, ::Headscale::V1::DeleteUserResponse
        rpc :ListUsers, ::Headscale::V1::ListUsersRequest, ::Headscale::V1::ListUsersResponse
        # --- PreAuthKeys start ---
        rpc :CreatePreAuthKey, ::Headscale::V1::CreatePreAuthKeyRequest, ::Headscale::V1::CreatePreAuthKeyResponse
        rpc :ExpirePreAuthKey, ::Headscale::V1::ExpirePreAuthKeyRequest, ::Headscale::V1::ExpirePreAuthKeyResponse
        rpc :ListPreAuthKeys, ::Headscale::V1::ListPreAuthKeysRequest, ::Headscale::V1::ListPreAuthKeysResponse
        # --- Node start ---
        rpc :DebugCreateNode, ::Headscale::V1::DebugCreateNodeRequest, ::Headscale::V1::DebugCreateNodeResponse
        rpc :GetNode, ::Headscale::V1::GetNodeRequest, ::Headscale::V1::GetNodeResponse
        rpc :SetTags, ::Headscale::V1::SetTagsRequest, ::Headscale::V1::SetTagsResponse
        rpc :SetApprovedRoutes, ::Headscale::V1::SetApprovedRoutesRequest, ::Headscale::V1::SetApprovedRoutesResponse
        rpc :RegisterNode, ::Headscale::V1::RegisterNodeRequest, ::Headscale::V1::RegisterNodeResponse
        rpc :DeleteNode, ::Headscale::V1::DeleteNodeRequest, ::Headscale::V1::DeleteNodeResponse
        rpc :ExpireNode, ::Headscale::V1::ExpireNodeRequest, ::Headscale::V1::ExpireNodeResponse
        rpc :RenameNode, ::Headscale::V1::RenameNodeRequest, ::Headscale::V1::RenameNodeResponse
        rpc :ListNodes, ::Headscale::V1::ListNodesRequest, ::Headscale::V1::ListNodesResponse
        rpc :MoveNode, ::Headscale::V1::MoveNodeRequest, ::Headscale::V1::MoveNodeResponse
        rpc :BackfillNodeIPs, ::Headscale::V1::BackfillNodeIPsRequest, ::Headscale::V1::BackfillNodeIPsResponse
        # --- Node end ---
        #
        # --- ApiKeys start ---
        rpc :CreateApiKey, ::Headscale::V1::CreateApiKeyRequest, ::Headscale::V1::CreateApiKeyResponse
        rpc :ExpireApiKey, ::Headscale::V1::ExpireApiKeyRequest, ::Headscale::V1::ExpireApiKeyResponse
        rpc :ListApiKeys, ::Headscale::V1::ListApiKeysRequest, ::Headscale::V1::ListApiKeysResponse
        rpc :DeleteApiKey, ::Headscale::V1::DeleteApiKeyRequest, ::Headscale::V1::DeleteApiKeyResponse
        # --- Policy start ---
        rpc :GetPolicy, ::Headscale::V1::GetPolicyRequest, ::Headscale::V1::GetPolicyResponse
        rpc :SetPolicy, ::Headscale::V1::SetPolicyRequest, ::Headscale::V1::SetPolicyResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
