# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/policy.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x19headscale/v1/policy.proto\x12\x0cheadscale.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n\x10SetPolicyRequest\x12\x0e\n\x06policy\x18\x01 \x01(\t\"S\n\x11SetPolicyResponse\x12\x0e\n\x06policy\x18\x01 \x01(\t\x12.\n\nupdated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x12\n\x10GetPolicyRequest\"S\n\x11GetPolicyResponse\x12\x0e\n\x06policy\x18\x01 \x01(\t\x12.\n\nupdated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB)Z\'github.com/juanfont/headscale/gen/go/v1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Headscale
  module V1
    SetPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.SetPolicyRequest").msgclass
    SetPolicyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.SetPolicyResponse").msgclass
    GetPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetPolicyRequest").msgclass
    GetPolicyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetPolicyResponse").msgclass
  end
end
