# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/preauthkey.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'headscale/v1/user_pb'


descriptor_data = "\n\x1dheadscale/v1/preauthkey.proto\x12\x0cheadscale.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17headscale/v1/user.proto\"\xec\x01\n\nPreAuthKey\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.headscale.v1.User\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x10\n\x08reusable\x18\x04 \x01(\x08\x12\x11\n\tephemeral\x18\x05 \x01(\x08\x12\x0c\n\x04used\x18\x06 \x01(\x08\x12.\n\nexpiration\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x61\x63l_tags\x18\t \x03(\t\"\x8e\x01\n\x17\x43reatePreAuthKeyRequest\x12\x0c\n\x04user\x18\x01 \x01(\x04\x12\x10\n\x08reusable\x18\x02 \x01(\x08\x12\x11\n\tephemeral\x18\x03 \x01(\x08\x12.\n\nexpiration\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x61\x63l_tags\x18\x05 \x03(\t\"J\n\x18\x43reatePreAuthKeyResponse\x12.\n\x0cpre_auth_key\x18\x01 \x01(\x0b\x32\x18.headscale.v1.PreAuthKey\"4\n\x17\x45xpirePreAuthKeyRequest\x12\x0c\n\x04user\x18\x01 \x01(\x04\x12\x0b\n\x03key\x18\x02 \x01(\t\"\x1a\n\x18\x45xpirePreAuthKeyResponse\"&\n\x16ListPreAuthKeysRequest\x12\x0c\n\x04user\x18\x01 \x01(\x04\"J\n\x17ListPreAuthKeysResponse\x12/\n\rpre_auth_keys\x18\x01 \x03(\x0b\x32\x18.headscale.v1.PreAuthKeyB)Z\'github.com/juanfont/headscale/gen/go/v1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Headscale
  module V1
    PreAuthKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.PreAuthKey").msgclass
    CreatePreAuthKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreatePreAuthKeyRequest").msgclass
    CreatePreAuthKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreatePreAuthKeyResponse").msgclass
    ExpirePreAuthKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ExpirePreAuthKeyRequest").msgclass
    ExpirePreAuthKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ExpirePreAuthKeyResponse").msgclass
    ListPreAuthKeysRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListPreAuthKeysRequest").msgclass
    ListPreAuthKeysResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListPreAuthKeysResponse").msgclass
  end
end
