# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/user.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x17headscale/v1/user.proto\x12\x0cheadscale.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x13\n\x0bprovider_id\x18\x06 \x01(\t\x12\x10\n\x08provider\x18\x07 \x01(\t\x12\x17\n\x0fprofile_pic_url\x18\x08 \x01(\t\"[\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x13\n\x0bpicture_url\x18\x04 \x01(\t\"6\n\x12\x43reateUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.headscale.v1.User\"5\n\x11RenameUserRequest\x12\x0e\n\x06old_id\x18\x01 \x01(\x04\x12\x10\n\x08new_name\x18\x02 \x01(\t\"6\n\x12RenameUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.headscale.v1.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"\x14\n\x12\x44\x65leteUserResponse\";\n\x10ListUsersRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"6\n\x11ListUsersResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.headscale.v1.UserB)Z\'github.com/juanfont/headscale/gen/go/v1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Headscale
  module V1
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.User").msgclass
    CreateUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreateUserRequest").msgclass
    CreateUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreateUserResponse").msgclass
    RenameUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.RenameUserRequest").msgclass
    RenameUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.RenameUserResponse").msgclass
    DeleteUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteUserRequest").msgclass
    DeleteUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteUserResponse").msgclass
    ListUsersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListUsersRequest").msgclass
    ListUsersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListUsersResponse").msgclass
  end
end
