# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/device.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("headscale/v1/device.proto", :syntax => :proto3) do
    add_message "headscale.v1.Latency" do
      optional :latency_ms, :float, 1
      optional :preferred, :bool, 2
    end
    add_message "headscale.v1.ClientSupports" do
      optional :hair_pinning, :bool, 1
      optional :ipv6, :bool, 2
      optional :pcp, :bool, 3
      optional :pmp, :bool, 4
      optional :udp, :bool, 5
      optional :upnp, :bool, 6
    end
    add_message "headscale.v1.ClientConnectivity" do
      repeated :endpoints, :string, 1
      optional :derp, :string, 2
      optional :mapping_varies_by_dest_ip, :bool, 3
      map :latency, :string, :message, 4, "headscale.v1.Latency"
      optional :client_supports, :message, 5, "headscale.v1.ClientSupports"
    end
    add_message "headscale.v1.GetDeviceRequest" do
      optional :id, :string, 1
    end
    add_message "headscale.v1.GetDeviceResponse" do
      repeated :addresses, :string, 1
      optional :id, :string, 2
      optional :user, :string, 3
      optional :name, :string, 4
      optional :hostname, :string, 5
      optional :client_version, :string, 6
      optional :update_available, :bool, 7
      optional :os, :string, 8
      optional :created, :message, 9, "google.protobuf.Timestamp"
      optional :last_seen, :message, 10, "google.protobuf.Timestamp"
      optional :key_expiry_disabled, :bool, 11
      optional :expires, :message, 12, "google.protobuf.Timestamp"
      optional :authorized, :bool, 13
      optional :is_external, :bool, 14
      optional :machine_key, :string, 15
      optional :node_key, :string, 16
      optional :blocks_incoming_connections, :bool, 17
      repeated :enabled_routes, :string, 18
      repeated :advertised_routes, :string, 19
      optional :client_connectivity, :message, 20, "headscale.v1.ClientConnectivity"
    end
    add_message "headscale.v1.DeleteDeviceRequest" do
      optional :id, :string, 1
    end
    add_message "headscale.v1.DeleteDeviceResponse" do
    end
    add_message "headscale.v1.GetDeviceRoutesRequest" do
      optional :id, :string, 1
    end
    add_message "headscale.v1.GetDeviceRoutesResponse" do
      repeated :enabled_routes, :string, 1
      repeated :advertised_routes, :string, 2
    end
    add_message "headscale.v1.EnableDeviceRoutesRequest" do
      optional :id, :string, 1
      repeated :routes, :string, 2
    end
    add_message "headscale.v1.EnableDeviceRoutesResponse" do
      repeated :enabled_routes, :string, 1
      repeated :advertised_routes, :string, 2
    end
  end
end

module Headscale
  module V1
    Latency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.Latency").msgclass
    ClientSupports = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ClientSupports").msgclass
    ClientConnectivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ClientConnectivity").msgclass
    GetDeviceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetDeviceRequest").msgclass
    GetDeviceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetDeviceResponse").msgclass
    DeleteDeviceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteDeviceRequest").msgclass
    DeleteDeviceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteDeviceResponse").msgclass
    GetDeviceRoutesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetDeviceRoutesRequest").msgclass
    GetDeviceRoutesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetDeviceRoutesResponse").msgclass
    EnableDeviceRoutesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.EnableDeviceRoutesRequest").msgclass
    EnableDeviceRoutesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.EnableDeviceRoutesResponse").msgclass
  end
end
