# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/headscale.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'headscale/v1/namespace_pb'
require 'headscale/v1/preauthkey_pb'
require 'headscale/v1/machine_pb'
require 'headscale/v1/routes_pb'
require 'headscale/v1/apikey_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("headscale/v1/headscale.proto", :syntax => :proto3) do
  end
end

module Headscale
  module V1
  end
end
