# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: headscale/v1/headscale.proto for package 'headscale.v1'

require 'grpc'
require 'headscale/v1/headscale_pb'

module Headscale
  module V1
    module HeadscaleService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'headscale.v1.HeadscaleService'

        # --- Namespace start ---
        rpc :GetNamespace, ::Headscale::V1::GetNamespaceRequest, ::Headscale::V1::GetNamespaceResponse
        rpc :CreateNamespace, ::Headscale::V1::CreateNamespaceRequest, ::Headscale::V1::CreateNamespaceResponse
        rpc :RenameNamespace, ::Headscale::V1::RenameNamespaceRequest, ::Headscale::V1::RenameNamespaceResponse
        rpc :DeleteNamespace, ::Headscale::V1::DeleteNamespaceRequest, ::Headscale::V1::DeleteNamespaceResponse
        rpc :ListNamespaces, ::Headscale::V1::ListNamespacesRequest, ::Headscale::V1::ListNamespacesResponse
        # --- PreAuthKeys start ---
        rpc :CreatePreAuthKey, ::Headscale::V1::CreatePreAuthKeyRequest, ::Headscale::V1::CreatePreAuthKeyResponse
        rpc :ExpirePreAuthKey, ::Headscale::V1::ExpirePreAuthKeyRequest, ::Headscale::V1::ExpirePreAuthKeyResponse
        rpc :ListPreAuthKeys, ::Headscale::V1::ListPreAuthKeysRequest, ::Headscale::V1::ListPreAuthKeysResponse
        # --- Machine start ---
        rpc :DebugCreateMachine, ::Headscale::V1::DebugCreateMachineRequest, ::Headscale::V1::DebugCreateMachineResponse
        rpc :GetMachine, ::Headscale::V1::GetMachineRequest, ::Headscale::V1::GetMachineResponse
        rpc :SetTags, ::Headscale::V1::SetTagsRequest, ::Headscale::V1::SetTagsResponse
        rpc :RegisterMachine, ::Headscale::V1::RegisterMachineRequest, ::Headscale::V1::RegisterMachineResponse
        rpc :DeleteMachine, ::Headscale::V1::DeleteMachineRequest, ::Headscale::V1::DeleteMachineResponse
        rpc :ExpireMachine, ::Headscale::V1::ExpireMachineRequest, ::Headscale::V1::ExpireMachineResponse
        rpc :RenameMachine, ::Headscale::V1::RenameMachineRequest, ::Headscale::V1::RenameMachineResponse
        rpc :ListMachines, ::Headscale::V1::ListMachinesRequest, ::Headscale::V1::ListMachinesResponse
        rpc :MoveMachine, ::Headscale::V1::MoveMachineRequest, ::Headscale::V1::MoveMachineResponse
        # --- Route start ---
        rpc :GetMachineRoute, ::Headscale::V1::GetMachineRouteRequest, ::Headscale::V1::GetMachineRouteResponse
        rpc :EnableMachineRoutes, ::Headscale::V1::EnableMachineRoutesRequest, ::Headscale::V1::EnableMachineRoutesResponse
        # --- ApiKeys start ---
        rpc :CreateApiKey, ::Headscale::V1::CreateApiKeyRequest, ::Headscale::V1::CreateApiKeyResponse
        rpc :ExpireApiKey, ::Headscale::V1::ExpireApiKeyRequest, ::Headscale::V1::ExpireApiKeyResponse
        rpc :ListApiKeys, ::Headscale::V1::ListApiKeysRequest, ::Headscale::V1::ListApiKeysResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
