# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/machine.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'headscale/v1/namespace_pb'
require 'headscale/v1/preauthkey_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("headscale/v1/machine.proto", :syntax => :proto3) do
    add_message "headscale.v1.Machine" do
      optional :id, :uint64, 1
      optional :machine_key, :string, 2
      optional :node_key, :string, 3
      optional :disco_key, :string, 4
      repeated :ip_addresses, :string, 5
      optional :name, :string, 6
      optional :namespace, :message, 7, "headscale.v1.Namespace"
      optional :last_seen, :message, 8, "google.protobuf.Timestamp"
      optional :last_successful_update, :message, 9, "google.protobuf.Timestamp"
      optional :expiry, :message, 10, "google.protobuf.Timestamp"
      optional :pre_auth_key, :message, 11, "headscale.v1.PreAuthKey"
      optional :created_at, :message, 12, "google.protobuf.Timestamp"
      optional :register_method, :enum, 13, "headscale.v1.RegisterMethod"
      repeated :forced_tags, :string, 18
      repeated :invalid_tags, :string, 19
      repeated :valid_tags, :string, 20
      optional :given_name, :string, 21
    end
    add_message "headscale.v1.RegisterMachineRequest" do
      optional :namespace, :string, 1
      optional :key, :string, 2
    end
    add_message "headscale.v1.RegisterMachineResponse" do
      optional :machine, :message, 1, "headscale.v1.Machine"
    end
    add_message "headscale.v1.GetMachineRequest" do
      optional :machine_id, :uint64, 1
    end
    add_message "headscale.v1.GetMachineResponse" do
      optional :machine, :message, 1, "headscale.v1.Machine"
    end
    add_message "headscale.v1.SetTagsRequest" do
      optional :machine_id, :uint64, 1
      repeated :tags, :string, 2
    end
    add_message "headscale.v1.SetTagsResponse" do
      optional :machine, :message, 1, "headscale.v1.Machine"
    end
    add_message "headscale.v1.DeleteMachineRequest" do
      optional :machine_id, :uint64, 1
    end
    add_message "headscale.v1.DeleteMachineResponse" do
    end
    add_message "headscale.v1.ExpireMachineRequest" do
      optional :machine_id, :uint64, 1
    end
    add_message "headscale.v1.ExpireMachineResponse" do
      optional :machine, :message, 1, "headscale.v1.Machine"
    end
    add_message "headscale.v1.RenameMachineRequest" do
      optional :machine_id, :uint64, 1
      optional :new_name, :string, 2
    end
    add_message "headscale.v1.RenameMachineResponse" do
      optional :machine, :message, 1, "headscale.v1.Machine"
    end
    add_message "headscale.v1.ListMachinesRequest" do
      optional :namespace, :string, 1
    end
    add_message "headscale.v1.ListMachinesResponse" do
      repeated :machines, :message, 1, "headscale.v1.Machine"
    end
    add_message "headscale.v1.MoveMachineRequest" do
      optional :machine_id, :uint64, 1
      optional :namespace, :string, 2
    end
    add_message "headscale.v1.MoveMachineResponse" do
      optional :machine, :message, 1, "headscale.v1.Machine"
    end
    add_message "headscale.v1.DebugCreateMachineRequest" do
      optional :namespace, :string, 1
      optional :key, :string, 2
      optional :name, :string, 3
      repeated :routes, :string, 4
    end
    add_message "headscale.v1.DebugCreateMachineResponse" do
      optional :machine, :message, 1, "headscale.v1.Machine"
    end
    add_enum "headscale.v1.RegisterMethod" do
      value :REGISTER_METHOD_UNSPECIFIED, 0
      value :REGISTER_METHOD_AUTH_KEY, 1
      value :REGISTER_METHOD_CLI, 2
      value :REGISTER_METHOD_OIDC, 3
    end
  end
end

module Headscale
  module V1
    Machine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.Machine").msgclass
    RegisterMachineRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.RegisterMachineRequest").msgclass
    RegisterMachineResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.RegisterMachineResponse").msgclass
    GetMachineRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetMachineRequest").msgclass
    GetMachineResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetMachineResponse").msgclass
    SetTagsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.SetTagsRequest").msgclass
    SetTagsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.SetTagsResponse").msgclass
    DeleteMachineRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteMachineRequest").msgclass
    DeleteMachineResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteMachineResponse").msgclass
    ExpireMachineRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ExpireMachineRequest").msgclass
    ExpireMachineResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ExpireMachineResponse").msgclass
    RenameMachineRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.RenameMachineRequest").msgclass
    RenameMachineResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.RenameMachineResponse").msgclass
    ListMachinesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListMachinesRequest").msgclass
    ListMachinesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListMachinesResponse").msgclass
    MoveMachineRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.MoveMachineRequest").msgclass
    MoveMachineResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.MoveMachineResponse").msgclass
    DebugCreateMachineRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DebugCreateMachineRequest").msgclass
    DebugCreateMachineResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DebugCreateMachineResponse").msgclass
    RegisterMethod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.RegisterMethod").enummodule
  end
end
