# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/namespace.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("headscale/v1/namespace.proto", :syntax => :proto3) do
    add_message "headscale.v1.Namespace" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
    end
    add_message "headscale.v1.GetNamespaceRequest" do
      optional :name, :string, 1
    end
    add_message "headscale.v1.GetNamespaceResponse" do
      optional :namespace, :message, 1, "headscale.v1.Namespace"
    end
    add_message "headscale.v1.CreateNamespaceRequest" do
      optional :name, :string, 1
    end
    add_message "headscale.v1.CreateNamespaceResponse" do
      optional :namespace, :message, 1, "headscale.v1.Namespace"
    end
    add_message "headscale.v1.RenameNamespaceRequest" do
      optional :old_name, :string, 1
      optional :new_name, :string, 2
    end
    add_message "headscale.v1.RenameNamespaceResponse" do
      optional :namespace, :message, 1, "headscale.v1.Namespace"
    end
    add_message "headscale.v1.DeleteNamespaceRequest" do
      optional :name, :string, 1
    end
    add_message "headscale.v1.DeleteNamespaceResponse" do
    end
    add_message "headscale.v1.ListNamespacesRequest" do
    end
    add_message "headscale.v1.ListNamespacesResponse" do
      repeated :namespaces, :message, 1, "headscale.v1.Namespace"
    end
  end
end

module Headscale
  module V1
    Namespace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.Namespace").msgclass
    GetNamespaceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetNamespaceRequest").msgclass
    GetNamespaceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetNamespaceResponse").msgclass
    CreateNamespaceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreateNamespaceRequest").msgclass
    CreateNamespaceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreateNamespaceResponse").msgclass
    RenameNamespaceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.RenameNamespaceRequest").msgclass
    RenameNamespaceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.RenameNamespaceResponse").msgclass
    DeleteNamespaceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteNamespaceRequest").msgclass
    DeleteNamespaceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.DeleteNamespaceResponse").msgclass
    ListNamespacesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListNamespacesRequest").msgclass
    ListNamespacesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListNamespacesResponse").msgclass
  end
end
