# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/preauthkey.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("headscale/v1/preauthkey.proto", :syntax => :proto3) do
    add_message "headscale.v1.PreAuthKey" do
      optional :namespace, :string, 1
      optional :id, :string, 2
      optional :key, :string, 3
      optional :reusable, :bool, 4
      optional :ephemeral, :bool, 5
      optional :used, :bool, 6
      optional :expiration, :message, 7, "google.protobuf.Timestamp"
      optional :created_at, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "headscale.v1.CreatePreAuthKeyRequest" do
      optional :namespace, :string, 1
      optional :reusable, :bool, 2
      optional :ephemeral, :bool, 3
      optional :expiration, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "headscale.v1.CreatePreAuthKeyResponse" do
      optional :pre_auth_key, :message, 1, "headscale.v1.PreAuthKey"
    end
    add_message "headscale.v1.ExpirePreAuthKeyRequest" do
      optional :namespace, :string, 1
      optional :key, :string, 2
    end
    add_message "headscale.v1.ExpirePreAuthKeyResponse" do
    end
    add_message "headscale.v1.ListPreAuthKeysRequest" do
      optional :namespace, :string, 1
    end
    add_message "headscale.v1.ListPreAuthKeysResponse" do
      repeated :pre_auth_keys, :message, 1, "headscale.v1.PreAuthKey"
    end
  end
end

module Headscale
  module V1
    PreAuthKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.PreAuthKey").msgclass
    CreatePreAuthKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreatePreAuthKeyRequest").msgclass
    CreatePreAuthKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.CreatePreAuthKeyResponse").msgclass
    ExpirePreAuthKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ExpirePreAuthKeyRequest").msgclass
    ExpirePreAuthKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ExpirePreAuthKeyResponse").msgclass
    ListPreAuthKeysRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListPreAuthKeysRequest").msgclass
    ListPreAuthKeysResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.ListPreAuthKeysResponse").msgclass
  end
end
