# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headscale/v1/routes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("headscale/v1/routes.proto", :syntax => :proto3) do
    add_message "headscale.v1.Routes" do
      repeated :advertised_routes, :string, 1
      repeated :enabled_routes, :string, 2
    end
    add_message "headscale.v1.GetMachineRouteRequest" do
      optional :machine_id, :uint64, 1
    end
    add_message "headscale.v1.GetMachineRouteResponse" do
      optional :routes, :message, 1, "headscale.v1.Routes"
    end
    add_message "headscale.v1.EnableMachineRoutesRequest" do
      optional :machine_id, :uint64, 1
      repeated :routes, :string, 2
    end
    add_message "headscale.v1.EnableMachineRoutesResponse" do
      optional :routes, :message, 1, "headscale.v1.Routes"
    end
  end
end

module Headscale
  module V1
    Routes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.Routes").msgclass
    GetMachineRouteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetMachineRouteRequest").msgclass
    GetMachineRouteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.GetMachineRouteResponse").msgclass
    EnableMachineRoutesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.EnableMachineRoutesRequest").msgclass
    EnableMachineRoutesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("headscale.v1.EnableMachineRoutesResponse").msgclass
  end
end
